spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/card?useSSL=false
    username: root
    password:
  thymeleaf:
    mode: LEGACYHTML5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8086
